/*
 * File: app.yaml
 * Project: UCHS
 * File Created: Sunday, 19th April 2020 11:57:44 am
 * Author: Abhirup Das (abhidash@outlook.com, https://github.com/maverickdas)
 * -----
 * Last Modified: Thursday, 18th June 2020 10:27:03 am
 * Modified By: Abhirup Das (abhidash@outlook.com, https://github.com/maverickdas)
 * -----
 * An Effort By: Team A.V.A.A.S., 2020
 */
# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: "root"
  CLOUD_SQL_PASSWORD: '#uchs1234'
  CLOUD_SQL_DATABASE_NAME: "uchs_db"
  TEST_DB_NAME: "uchs_test"
  CLOUD_SQL_CONNECTION_NAME: "tribal-marker-274610:asia-south1:uchs-db"
# [END gae_python37_cloudsql_config]
