# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: "root"
  CLOUD_SQL_PASSWORD: '#uchs1234'
  CLOUD_SQL_DATABASE_NAME: "book"
  CLOUD_SQL_CONNECTION_NAME: "tribal-marker-274610:asia-south1:uchs-db"
# [END gae_python37_cloudsql_config]
